packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  '@depot/cli': true
  bcrypt: true
  esbuild: true
  protobufjs: true
  sharp: true
  unrs-resolver: true

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
