export type EmojiItem = {
  char: string
  keywords: string[]
}

export type EmojiCategoryId =
  | 'recent'
  | 'smileys'
  | 'people'
  | 'animals'
  | 'food'
  | 'travel'
  | 'activities'
  | 'objects'
  | 'symbols'
  | 'flags'

export type EmojiCategory = {
  id: EmojiCategoryId
  label: string
  emojis: EmojiItem[]
}

export const EMOJI_RECENT_STORAGE_KEY = 'socialista:emoji-recent:v1'
export const EMOJI_RECENT_MAX = 24

function dedupeEmojiItems(items: EmojiItem[]): EmojiItem[] {
  const seen = new Set<string>()
  const deduped: EmojiItem[] = []

  for (const item of items) {
    if (seen.has(item.char)) continue
    seen.add(item.char)
    deduped.push(item)
  }

  return deduped
}

const EMOJI_CATEGORIES_SOURCE: EmojiCategory[] = [
  {
    id: 'smileys',
    label: 'Smileys',
    emojis: [
      { char: '😀', keywords: ['grin', 'happy', 'smile'] },
      { char: '😃', keywords: ['smile', 'happy', 'joy'] },
      { char: '😄', keywords: ['smile', 'happy', 'laugh'] },
      { char: '😁', keywords: ['grin', 'happy'] },
      { char: '😆', keywords: ['laugh', 'happy'] },
      { char: '😅', keywords: ['sweat', 'laugh', 'nervous'] },
      { char: '🤣', keywords: ['rofl', 'laugh', 'lol'] },
      { char: '😂', keywords: ['joy', 'tears', 'laugh', 'lol'] },
      { char: '🙂', keywords: ['smile', 'slight'] },
      { char: '🙃', keywords: ['upside', 'silly'] },
      { char: '😉', keywords: ['wink', 'flirt'] },
      { char: '😊', keywords: ['blush', 'smile', 'happy'] },
      { char: '😇', keywords: ['angel', 'innocent'] },
      { char: '🥰', keywords: ['love', 'hearts', 'smile'] },
      { char: '😍', keywords: ['love', 'heart', 'eyes'] },
      { char: '🤩', keywords: ['star', 'eyes', 'excited'] },
      { char: '😘', keywords: ['kiss', 'love'] },
      { char: '😗', keywords: ['kiss'] },
      { char: '😚', keywords: ['kiss', 'blush'] },
      { char: '😙', keywords: ['kiss', 'smile'] },
      { char: '🥲', keywords: ['smile', 'tear', 'grateful'] },
      { char: '😋', keywords: ['yum', 'delicious', 'tongue'] },
      { char: '😛', keywords: ['tongue', 'playful'] },
      { char: '😜', keywords: ['wink', 'tongue', 'crazy'] },
      { char: '🤪', keywords: ['zany', 'crazy', 'wild'] },
      { char: '😝', keywords: ['tongue', 'squint'] },
      { char: '🤑', keywords: ['money', 'rich'] },
      { char: '🤗', keywords: ['hug', 'warm'] },
      { char: '🤭', keywords: ['giggle', 'oops'] },
      { char: '🤫', keywords: ['shh', 'quiet', 'secret'] },
      { char: '🤔', keywords: ['think', 'hmm', 'consider'] },
      { char: '🤐', keywords: ['zipper', 'quiet', 'secret'] },
      { char: '🤨', keywords: ['skeptical', 'raised', 'eyebrow'] },
      { char: '😐', keywords: ['neutral', 'meh'] },
      { char: '😑', keywords: ['expressionless', 'blank'] },
      { char: '😶', keywords: ['silent', 'speechless'] },
      { char: '😏', keywords: ['smirk', 'sly'] },
      { char: '😒', keywords: ['unamused', 'bored'] },
      { char: '🙄', keywords: ['eye', 'roll', 'annoyed'] },
      { char: '😬', keywords: ['grimace', 'awkward'] },
      { char: '😮‍💨', keywords: ['sigh', 'exhale', 'relief'] },
      { char: '🤥', keywords: ['lie', 'pinocchio'] },
      { char: '😌', keywords: ['relieved', 'calm', 'peace'] },
      { char: '😔', keywords: ['sad', 'pensive'] },
      { char: '😪', keywords: ['sleepy', 'tired'] },
      { char: '🤤', keywords: ['drool', 'hungry'] },
      { char: '😴', keywords: ['sleep', 'zzz', 'tired'] },
      { char: '😷', keywords: ['mask', 'sick'] },
      { char: '🤒', keywords: ['sick', 'fever', 'thermometer'] },
      { char: '🤕', keywords: ['hurt', 'bandage'] },
      { char: '🤢', keywords: ['nauseated', 'sick'] },
      { char: '🤮', keywords: ['vomit', 'sick'] },
      { char: '🤧', keywords: ['sneeze', 'sick'] },
      { char: '🥵', keywords: ['hot', 'sweat'] },
      { char: '🥶', keywords: ['cold', 'freeze'] },
      { char: '🥴', keywords: ['woozy', 'dizzy', 'drunk'] },
      { char: '😵', keywords: ['dizzy', 'dead'] },
      { char: '🤯', keywords: ['mind', 'blown', 'shock'] },
      { char: '🤠', keywords: ['cowboy', 'hat'] },
      { char: '🥳', keywords: ['party', 'celebrate', 'birthday'] },
      { char: '🥸', keywords: ['disguise', 'glasses'] },
      { char: '😎', keywords: ['cool', 'sunglasses'] },
      { char: '🤓', keywords: ['nerd', 'geek', 'glasses'] },
      { char: '🧐', keywords: ['monocle', 'inspect'] },
      { char: '😕', keywords: ['confused', 'sad'] },
      { char: '😟', keywords: ['worried', 'concerned'] },
      { char: '🙁', keywords: ['frown', 'sad'] },
      { char: '☹️', keywords: ['frown', 'sad'] },
      { char: '😮', keywords: ['open', 'mouth', 'surprise'] },
      { char: '😯', keywords: ['hushed', 'surprise'] },
      { char: '😲', keywords: ['astonished', 'shock'] },
      { char: '😳', keywords: ['flushed', 'embarrassed'] },
      { char: '🥺', keywords: ['pleading', 'puppy', 'eyes', 'please'] },
      { char: '😦', keywords: ['frown', 'open', 'mouth'] },
      { char: '😧', keywords: ['anguished', 'shock'] },
      { char: '😨', keywords: ['fearful', 'scared'] },
      { char: '😰', keywords: ['anxious', 'sweat'] },
      { char: '😥', keywords: ['sad', 'relieved', 'sweat'] },
      { char: '😢', keywords: ['cry', 'tear', 'sad'] },
      { char: '😭', keywords: ['sob', 'cry', 'tears'] },
      { char: '😱', keywords: ['scream', 'fear', 'shock'] },
      { char: '😖', keywords: ['confounded', 'frustrated'] },
      { char: '😣', keywords: ['persevere', 'struggle'] },
      { char: '😞', keywords: ['disappointed', 'sad'] },
      { char: '😓', keywords: ['sweat', 'sad'] },
      { char: '😩', keywords: ['weary', 'tired'] },
      { char: '😫', keywords: ['tired', 'exhausted'] },
      { char: '🥱', keywords: ['yawn', 'tired', 'bored'] },
      { char: '😤', keywords: ['triumph', 'angry', 'steam'] },
      { char: '😡', keywords: ['angry', 'mad', 'rage'] },
      { char: '😠', keywords: ['angry', 'mad'] },
      { char: '🤬', keywords: ['swear', 'angry', 'cursing'] },
      { char: '😈', keywords: ['devil', 'evil', 'smile'] },
      { char: '👿', keywords: ['devil', 'angry', 'imp'] },
      { char: '💀', keywords: ['skull', 'dead'] },
      { char: '☠️', keywords: ['skull', 'crossbones', 'danger'] },
      { char: '💩', keywords: ['poop', 'funny'] },
      { char: '🤡', keywords: ['clown', 'funny'] },
      { char: '👹', keywords: ['ogre', 'monster'] },
      { char: '👺', keywords: ['goblin', 'monster'] },
      { char: '👻', keywords: ['ghost', 'halloween', 'boo'] },
      { char: '👽', keywords: ['alien', 'ufo', 'space'] },
      { char: '🤖', keywords: ['robot', 'bot', 'ai'] },
    ],
  },
  {
    id: 'people',
    label: 'People',
    emojis: [
      { char: '👋', keywords: ['wave', 'hello', 'hi', 'bye'] },
      { char: '🤚', keywords: ['raised', 'back', 'hand'] },
      { char: '🖐️', keywords: ['hand', 'fingers', 'five'] },
      { char: '✋', keywords: ['stop', 'hand', 'high five'] },
      { char: '🖖', keywords: ['vulcan', 'spock', 'star trek'] },
      { char: '👌', keywords: ['ok', 'perfect', 'good'] },
      { char: '🤌', keywords: ['pinched', 'italian'] },
      { char: '🤏', keywords: ['pinch', 'small', 'tiny'] },
      { char: '✌️', keywords: ['peace', 'victory', 'two'] },
      { char: '🤞', keywords: ['cross', 'fingers', 'luck', 'hope'] },
      { char: '🤟', keywords: ['love', 'you', 'rock'] },
      { char: '🤘', keywords: ['rock', 'metal', 'horns'] },
      { char: '🤙', keywords: ['call', 'shaka', 'hang loose'] },
      { char: '👈', keywords: ['point', 'left'] },
      { char: '👉', keywords: ['point', 'right'] },
      { char: '👆', keywords: ['point', 'up'] },
      { char: '👇', keywords: ['point', 'down'] },
      { char: '☝️', keywords: ['point', 'up', 'one'] },
      { char: '👍', keywords: ['thumbs', 'up', 'like', 'yes', 'good'] },
      { char: '👎', keywords: ['thumbs', 'down', 'dislike', 'no', 'bad'] },
      { char: '✊', keywords: ['fist', 'power', 'solidarity'] },
      { char: '👊', keywords: ['punch', 'fist', 'bump'] },
      { char: '🤛', keywords: ['fist', 'left'] },
      { char: '🤜', keywords: ['fist', 'right'] },
      { char: '👏', keywords: ['clap', 'applause', 'bravo'] },
      { char: '🙌', keywords: ['raise', 'hands', 'celebrate', 'hooray'] },
      { char: '👐', keywords: ['open', 'hands'] },
      { char: '🤲', keywords: ['palms', 'up', 'pray'] },
      { char: '🤝', keywords: ['handshake', 'deal', 'agreement'] },
      { char: '🙏', keywords: ['pray', 'please', 'thanks', 'namaste'] },
      { char: '✍️', keywords: ['write', 'sign'] },
      { char: '💅', keywords: ['nails', 'manicure', 'slay'] },
      { char: '🤳', keywords: ['selfie', 'phone'] },
      { char: '💪', keywords: ['muscle', 'strong', 'flex', 'gym'] },
      { char: '🦾', keywords: ['prosthetic', 'arm', 'strong'] },
      { char: '🦵', keywords: ['leg', 'kick'] },
      { char: '🦶', keywords: ['foot', 'kick'] },
      { char: '👂', keywords: ['ear', 'listen', 'hear'] },
      { char: '👃', keywords: ['nose', 'smell'] },
      { char: '🧠', keywords: ['brain', 'smart', 'think'] },
      { char: '🫀', keywords: ['heart', 'organ'] },
      { char: '👀', keywords: ['eyes', 'look', 'see', 'watch'] },
      { char: '👁️', keywords: ['eye', 'see'] },
      { char: '👅', keywords: ['tongue', 'taste'] },
      { char: '👄', keywords: ['mouth', 'lips', 'kiss'] },
      { char: '👶', keywords: ['baby', 'child'] },
      { char: '🧒', keywords: ['child', 'kid'] },
      { char: '👦', keywords: ['boy', 'child'] },
      { char: '👧', keywords: ['girl', 'child'] },
      { char: '🧑', keywords: ['person', 'adult'] },
      { char: '👱', keywords: ['blond', 'person'] },
      { char: '👨', keywords: ['man', 'male'] },
      { char: '👩', keywords: ['woman', 'female'] },
      { char: '🧓', keywords: ['older', 'elderly'] },
      { char: '👴', keywords: ['old', 'man', 'grandpa'] },
      { char: '👵', keywords: ['old', 'woman', 'grandma'] },
      { char: '🙍', keywords: ['frown', 'person'] },
      { char: '🙎', keywords: ['pout', 'person'] },
      { char: '🙅', keywords: ['no', 'gesture', 'stop'] },
      { char: '🙆', keywords: ['ok', 'gesture', 'yes'] },
      { char: '💁', keywords: ['information', 'sassy'] },
      { char: '🙋', keywords: ['raise', 'hand', 'question'] },
      { char: '🧏', keywords: ['deaf', 'person'] },
      { char: '🙇', keywords: ['bow', 'sorry', 'respect'] },
      { char: '🤦', keywords: ['facepalm', 'disappointed'] },
      { char: '🤷', keywords: ['shrug', 'idk', 'dunno'] },
      { char: '👮', keywords: ['police', 'cop'] },
      { char: '💂', keywords: ['guard'] },
      { char: '🕵️', keywords: ['detective', 'spy'] },
      { char: '👷', keywords: ['construction', 'worker', 'builder'] },
      { char: '🤴', keywords: ['prince', 'royal'] },
      { char: '👸', keywords: ['princess', 'royal'] },
      { char: '👳', keywords: ['turban'] },
      { char: '👲', keywords: ['hat', 'chinese'] },
      { char: '🧕', keywords: ['hijab', 'woman'] },
      { char: '🤵', keywords: ['tuxedo', 'formal', 'wedding'] },
      { char: '👰', keywords: ['bride', 'wedding', 'veil'] },
      { char: '🤰', keywords: ['pregnant', 'woman'] },
      { char: '🤱', keywords: ['breastfeeding', 'baby'] },
      { char: '👼', keywords: ['angel', 'baby'] },
      { char: '🎅', keywords: ['santa', 'christmas'] },
      { char: '🤶', keywords: ['mrs', 'claus', 'christmas'] },
      { char: '🦸', keywords: ['superhero', 'hero'] },
      { char: '🦹', keywords: ['supervillain', 'villain'] },
      { char: '🧙', keywords: ['wizard', 'magic'] },
      { char: '🧚', keywords: ['fairy', 'magic'] },
      { char: '🧛', keywords: ['vampire'] },
      { char: '🧜', keywords: ['mermaid'] },
      { char: '🧝', keywords: ['elf'] },
      { char: '🧞', keywords: ['genie', 'wish'] },
      { char: '🧟', keywords: ['zombie'] },
      { char: '💆', keywords: ['massage', 'spa'] },
      { char: '💇', keywords: ['haircut', 'salon'] },
      { char: '🚶', keywords: ['walk', 'walking'] },
      { char: '🧍', keywords: ['stand', 'standing'] },
      { char: '🧎', keywords: ['kneel'] },
      { char: '🏃', keywords: ['run', 'running', 'jog'] },
      { char: '💃', keywords: ['dance', 'woman'] },
      { char: '🕺', keywords: ['dance', 'man'] },
      { char: '🕴️', keywords: ['levitate', 'business'] },
      { char: '👯', keywords: ['bunny', 'ears', 'party'] },
      { char: '🧖', keywords: ['sauna', 'steam'] },
      { char: '🧗', keywords: ['climb', 'climbing'] },
      { char: '🤺', keywords: ['fencing', 'sword'] },
      { char: '🏇', keywords: ['horse', 'racing'] },
      { char: '⛷️', keywords: ['ski', 'skiing'] },
      { char: '🏂', keywords: ['snowboard'] },
      { char: '🏌️', keywords: ['golf'] },
      { char: '🏄', keywords: ['surf', 'surfing'] },
      { char: '🚣', keywords: ['row', 'boat'] },
      { char: '🏊', keywords: ['swim', 'swimming'] },
      { char: '⛹️', keywords: ['basketball'] },
      { char: '🏋️', keywords: ['weight', 'lift', 'gym'] },
      { char: '🚴', keywords: ['bike', 'cycling'] },
      { char: '🚵', keywords: ['mountain', 'bike'] },
      { char: '🤸', keywords: ['cartwheel', 'gymnastics'] },
      { char: '🤼', keywords: ['wrestle'] },
      { char: '🤽', keywords: ['water', 'polo'] },
      { char: '🤾', keywords: ['handball'] },
      { char: '🤹', keywords: ['juggle'] },
      { char: '🧘', keywords: ['yoga', 'meditate'] },
      { char: '🛀', keywords: ['bath', 'relax'] },
      { char: '🛌', keywords: ['sleep', 'bed'] },
      { char: '👫', keywords: ['couple', 'hold', 'hands'] },
      { char: '👬', keywords: ['men', 'couple'] },
      { char: '👭', keywords: ['women', 'couple'] },
      { char: '💏', keywords: ['kiss', 'couple'] },
      { char: '💑', keywords: ['couple', 'love'] },
      { char: '👪', keywords: ['family'] },
      { char: '🗣️', keywords: ['speak', 'talk'] },
      { char: '👤', keywords: ['silhouette', 'person'] },
      { char: '👥', keywords: ['people', 'group', 'team'] },
    ],
  },
  {
    id: 'animals',
    label: 'Animals',
    emojis: [
      { char: '🐶', keywords: ['dog', 'puppy', 'pet'] },
      { char: '🐱', keywords: ['cat', 'kitten', 'pet'] },
      { char: '🐭', keywords: ['mouse', 'rat'] },
      { char: '🐹', keywords: ['hamster', 'pet'] },
      { char: '🐰', keywords: ['rabbit', 'bunny'] },
      { char: '🦊', keywords: ['fox'] },
      { char: '🐻', keywords: ['bear'] },
      { char: '🐼', keywords: ['panda'] },
      { char: '🐻‍❄️', keywords: ['polar', 'bear'] },
      { char: '🐨', keywords: ['koala'] },
      { char: '🐯', keywords: ['tiger'] },
      { char: '🦁', keywords: ['lion'] },
      { char: '🐮', keywords: ['cow'] },
      { char: '🐷', keywords: ['pig'] },
      { char: '🐸', keywords: ['frog'] },
      { char: '🐵', keywords: ['monkey'] },
      { char: '🙈', keywords: ['see', 'no', 'evil', 'monkey'] },
      { char: '🙉', keywords: ['hear', 'no', 'evil', 'monkey'] },
      { char: '🙊', keywords: ['speak', 'no', 'evil', 'monkey'] },
      { char: '🐒', keywords: ['monkey'] },
      { char: '🐔', keywords: ['chicken', 'rooster'] },
      { char: '🐧', keywords: ['penguin'] },
      { char: '🐦', keywords: ['bird'] },
      { char: '🐤', keywords: ['chick', 'baby'] },
      { char: '🦆', keywords: ['duck'] },
      { char: '🦅', keywords: ['eagle', 'bird'] },
      { char: '🦉', keywords: ['owl', 'wise'] },
      { char: '🦇', keywords: ['bat', 'halloween'] },
      { char: '🐺', keywords: ['wolf'] },
      { char: '🐗', keywords: ['boar', 'pig'] },
      { char: '🐴', keywords: ['horse'] },
      { char: '🦄', keywords: ['unicorn', 'magic'] },
      { char: '🐝', keywords: ['bee', 'honey', 'buzz'] },
      { char: '🪱', keywords: ['worm'] },
      { char: '🐛', keywords: ['bug', 'caterpillar'] },
      { char: '🦋', keywords: ['butterfly'] },
      { char: '🐌', keywords: ['snail', 'slow'] },
      { char: '🐞', keywords: ['ladybug', 'bug'] },
      { char: '🐜', keywords: ['ant', 'bug'] },
      { char: '🦟', keywords: ['mosquito', 'bug'] },
      { char: '🦗', keywords: ['cricket', 'bug'] },
      { char: '🕷️', keywords: ['spider', 'web'] },
      { char: '🦂', keywords: ['scorpion'] },
      { char: '🐢', keywords: ['turtle', 'slow'] },
      { char: '🐍', keywords: ['snake'] },
      { char: '🦎', keywords: ['lizard'] },
      { char: '🦖', keywords: ['t-rex', 'dinosaur'] },
      { char: '🦕', keywords: ['dinosaur', 'sauropod'] },
      { char: '🐙', keywords: ['octopus'] },
      { char: '🦑', keywords: ['squid'] },
      { char: '🦐', keywords: ['shrimp', 'seafood'] },
      { char: '🦞', keywords: ['lobster', 'seafood'] },
      { char: '🦀', keywords: ['crab', 'seafood'] },
      { char: '🐡', keywords: ['blowfish', 'fish'] },
      { char: '🐠', keywords: ['fish', 'tropical'] },
      { char: '🐟', keywords: ['fish'] },
      { char: '🐬', keywords: ['dolphin'] },
      { char: '🐳', keywords: ['whale', 'spout'] },
      { char: '🐋', keywords: ['whale'] },
      { char: '🦈', keywords: ['shark'] },
      { char: '🐊', keywords: ['crocodile', 'alligator'] },
      { char: '🐅', keywords: ['tiger'] },
      { char: '🐆', keywords: ['leopard'] },
      { char: '🦓', keywords: ['zebra'] },
      { char: '🦍', keywords: ['gorilla'] },
      { char: '🦧', keywords: ['orangutan'] },
      { char: '🐘', keywords: ['elephant'] },
      { char: '🦛', keywords: ['hippo'] },
      { char: '🦏', keywords: ['rhino'] },
      { char: '🐪', keywords: ['camel'] },
      { char: '🦒', keywords: ['giraffe'] },
      { char: '🦘', keywords: ['kangaroo'] },
      { char: '🐃', keywords: ['buffalo'] },
      { char: '🐂', keywords: ['ox'] },
      { char: '🐄', keywords: ['cow'] },
      { char: '🐎', keywords: ['horse', 'racing'] },
      { char: '🐖', keywords: ['pig'] },
      { char: '🐏', keywords: ['ram', 'sheep'] },
      { char: '🐑', keywords: ['sheep', 'lamb'] },
      { char: '🦙', keywords: ['llama', 'alpaca'] },
      { char: '🐐', keywords: ['goat'] },
      { char: '🦌', keywords: ['deer'] },
      { char: '🐕', keywords: ['dog'] },
      { char: '🐩', keywords: ['poodle', 'dog'] },
      { char: '🦮', keywords: ['guide', 'dog'] },
      { char: '🐈', keywords: ['cat'] },
      { char: '🐓', keywords: ['rooster'] },
      { char: '🦃', keywords: ['turkey', 'thanksgiving'] },
      { char: '🦚', keywords: ['peacock'] },
      { char: '🦜', keywords: ['parrot'] },
      { char: '🦢', keywords: ['swan'] },
      { char: '🕊️', keywords: ['dove', 'peace'] },
      { char: '🐇', keywords: ['rabbit'] },
      { char: '🦝', keywords: ['raccoon'] },
      { char: '🦨', keywords: ['skunk'] },
      { char: '🦡', keywords: ['badger'] },
      { char: '🦫', keywords: ['beaver'] },
      { char: '🦦', keywords: ['otter'] },
      { char: '🦥', keywords: ['sloth', 'slow'] },
      { char: '🐁', keywords: ['mouse'] },
      { char: '🐀', keywords: ['rat'] },
      { char: '🐿️', keywords: ['chipmunk', 'squirrel'] },
      { char: '🦔', keywords: ['hedgehog'] },
      { char: '🐾', keywords: ['paw', 'prints', 'pet'] },
      { char: '🐉', keywords: ['dragon'] },
      { char: '🐲', keywords: ['dragon', 'face'] },
      { char: '🌵', keywords: ['cactus', 'desert', 'plant'] },
      { char: '🎄', keywords: ['christmas', 'tree'] },
      { char: '🌲', keywords: ['tree', 'evergreen'] },
      { char: '🌳', keywords: ['tree', 'deciduous'] },
      { char: '🌴', keywords: ['palm', 'tree', 'tropical'] },
      { char: '🌱', keywords: ['seedling', 'plant', 'grow'] },
      { char: '🌿', keywords: ['herb', 'leaf', 'plant'] },
      { char: '☘️', keywords: ['shamrock', 'luck', 'irish'] },
      { char: '🍀', keywords: ['clover', 'luck', 'four leaf'] },
      { char: '🍁', keywords: ['maple', 'leaf', 'fall', 'autumn'] },
      { char: '🍂', keywords: ['leaves', 'fall', 'autumn'] },
      { char: '🍃', keywords: ['leaf', 'wind', 'blow'] },
      { char: '🌺', keywords: ['hibiscus', 'flower'] },
      { char: '🌸', keywords: ['cherry', 'blossom', 'flower', 'spring'] },
      { char: '💮', keywords: ['flower', 'white'] },
      { char: '🏵️', keywords: ['rosette', 'flower'] },
      { char: '🌹', keywords: ['rose', 'flower', 'love'] },
      { char: '🥀', keywords: ['wilted', 'flower', 'sad'] },
      { char: '🌻', keywords: ['sunflower', 'flower'] },
      { char: '🌼', keywords: ['blossom', 'flower'] },
      { char: '🌷', keywords: ['tulip', 'flower', 'spring'] },
      { char: '🌾', keywords: ['rice', 'grain', 'harvest'] },
      { char: '💐', keywords: ['bouquet', 'flowers', 'gift'] },
      { char: '🍄', keywords: ['mushroom'] },
      { char: '🌰', keywords: ['chestnut'] },
      { char: '🪴', keywords: ['potted', 'plant'] },
      { char: '🌍', keywords: ['earth', 'globe', 'africa', 'europe'] },
      { char: '🌎', keywords: ['earth', 'globe', 'americas'] },
      { char: '🌏', keywords: ['earth', 'globe', 'asia', 'australia'] },
      { char: '🌕', keywords: ['full', 'moon'] },
      { char: '🌖', keywords: ['moon', 'waning'] },
      { char: '🌗', keywords: ['moon', 'last', 'quarter'] },
      { char: '🌘', keywords: ['moon', 'crescent'] },
      { char: '🌑', keywords: ['new', 'moon', 'dark'] },
      { char: '🌒', keywords: ['moon', 'waxing'] },
      { char: '🌓', keywords: ['moon', 'first', 'quarter'] },
      { char: '🌔', keywords: ['moon', 'waxing'] },
      { char: '🌙', keywords: ['crescent', 'moon', 'night'] },
      { char: '🌚', keywords: ['new', 'moon', 'face'] },
      { char: '🌛', keywords: ['moon', 'face', 'first', 'quarter'] },
      { char: '🌜', keywords: ['moon', 'face', 'last', 'quarter'] },
      { char: '☀️', keywords: ['sun', 'sunny', 'bright'] },
      { char: '🌝', keywords: ['full', 'moon', 'face'] },
      { char: '🌞', keywords: ['sun', 'face', 'hot'] },
      { char: '⭐', keywords: ['star'] },
      { char: '🌟', keywords: ['star', 'glow', 'sparkle'] },
      { char: '✨', keywords: ['sparkles', 'shine', 'magic'] },
      { char: '⚡', keywords: ['lightning', 'bolt', 'fast', 'energy'] },
      { char: '🔥', keywords: ['fire', 'hot', 'lit', 'flame'] },
      { char: '💥', keywords: ['boom', 'explosion', 'bang'] },
      { char: '☄️', keywords: ['comet', 'space'] },
      { char: '🌈', keywords: ['rainbow', 'pride', 'colorful'] },
      { char: '☁️', keywords: ['cloud'] },
      { char: '⛅', keywords: ['sun', 'cloud', 'partly'] },
      { char: '⛈️', keywords: ['storm', 'thunder', 'rain'] },
      { char: '🌤️', keywords: ['sun', 'cloud', 'small'] },
      { char: '🌥️', keywords: ['sun', 'cloud', 'large'] },
      { char: '🌦️', keywords: ['sun', 'rain', 'shower'] },
      { char: '🌧️', keywords: ['rain', 'cloud'] },
      { char: '⛈️', keywords: ['thunder', 'storm'] },
      { char: '🌩️', keywords: ['lightning', 'cloud'] },
      { char: '🌨️', keywords: ['snow', 'cloud'] },
      { char: '❄️', keywords: ['snowflake', 'cold', 'winter'] },
      { char: '☃️', keywords: ['snowman', 'winter'] },
      { char: '⛄', keywords: ['snowman', 'winter'] },
      { char: '🌬️', keywords: ['wind', 'blow'] },
      { char: '💨', keywords: ['dash', 'wind', 'fast', 'smoke'] },
      { char: '💧', keywords: ['droplet', 'water', 'tear'] },
      { char: '💦', keywords: ['sweat', 'droplets', 'water'] },
      { char: '☔', keywords: ['umbrella', 'rain'] },
      { char: '☂️', keywords: ['umbrella'] },
      { char: '🌊', keywords: ['wave', 'ocean', 'water', 'sea'] },
      { char: '🌫️', keywords: ['fog', 'mist'] },
    ],
  },
  {
    id: 'food',
    label: 'Food',
    emojis: [
      { char: '🍎', keywords: ['apple', 'fruit', 'red'] },
      { char: '🍊', keywords: ['orange', 'tangerine', 'fruit'] },
      { char: '🍋', keywords: ['lemon', 'fruit', 'citrus'] },
      { char: '🍌', keywords: ['banana', 'fruit'] },
      { char: '🍉', keywords: ['watermelon', 'fruit'] },
      { char: '🍇', keywords: ['grapes', 'fruit'] },
      { char: '🍓', keywords: ['strawberry', 'fruit', 'berry'] },
      { char: '🫐', keywords: ['blueberry', 'berry'] },
      { char: '🍑', keywords: ['peach', 'fruit'] },
      { char: '🍒', keywords: ['cherry', 'fruit'] },
      { char: '🥝', keywords: ['kiwi', 'fruit'] },
      { char: '🍍', keywords: ['pineapple', 'fruit', 'tropical'] },
      { char: '🥭', keywords: ['mango', 'fruit', 'tropical'] },
      { char: '🥑', keywords: ['avocado'] },
      { char: '🍅', keywords: ['tomato', 'vegetable'] },
      { char: '🥕', keywords: ['carrot', 'vegetable'] },
      { char: '🌽', keywords: ['corn', 'vegetable'] },
      { char: '🌶️', keywords: ['pepper', 'hot', 'spicy'] },
      { char: '🥦', keywords: ['broccoli', 'vegetable'] },
      { char: '🍞', keywords: ['bread', 'toast'] },
      { char: '🥐', keywords: ['croissant', 'bread', 'french'] },
      { char: '🥖', keywords: ['baguette', 'bread'] },
      { char: '🥨', keywords: ['pretzel'] },
      { char: '🥯', keywords: ['bagel'] },
      { char: '🥞', keywords: ['pancakes', 'breakfast'] },
      { char: '🧇', keywords: ['waffle', 'breakfast'] },
      { char: '🧀', keywords: ['cheese'] },
      { char: '🍖', keywords: ['meat', 'bone'] },
      { char: '🍗', keywords: ['chicken', 'leg', 'poultry'] },
      { char: '🥩', keywords: ['steak', 'meat'] },
      { char: '🥓', keywords: ['bacon', 'breakfast'] },
      { char: '🍔', keywords: ['burger', 'hamburger', 'fast food'] },
      { char: '🍟', keywords: ['fries', 'french', 'fast food'] },
      { char: '🍕', keywords: ['pizza', 'slice'] },
      { char: '🌭', keywords: ['hotdog', 'sausage'] },
      { char: '🥪', keywords: ['sandwich'] },
      { char: '🌮', keywords: ['taco', 'mexican'] },
      { char: '🌯', keywords: ['burrito', 'wrap', 'mexican'] },
      { char: '🥗', keywords: ['salad', 'healthy', 'green'] },
      { char: '🍿', keywords: ['popcorn', 'movie', 'snack'] },
      { char: '🍱', keywords: ['bento', 'lunch', 'japanese'] },
      { char: '🍜', keywords: ['ramen', 'noodles', 'soup'] },
      { char: '🍝', keywords: ['spaghetti', 'pasta', 'italian'] },
      { char: '🍣', keywords: ['sushi', 'japanese'] },
      { char: '🍤', keywords: ['shrimp', 'fried'] },
      { char: '🍦', keywords: ['ice', 'cream', 'dessert'] },
      { char: '🍩', keywords: ['donut', 'doughnut', 'dessert'] },
      { char: '🍪', keywords: ['cookie', 'dessert'] },
      { char: '🎂', keywords: ['birthday', 'cake', 'dessert'] },
      { char: '🍰', keywords: ['cake', 'slice', 'dessert'] },
      { char: '🧁', keywords: ['cupcake', 'dessert'] },
      { char: '🍫', keywords: ['chocolate', 'candy'] },
      { char: '🍬', keywords: ['candy', 'sweet'] },
      { char: '🍭', keywords: ['lollipop', 'candy'] },
      { char: '🍯', keywords: ['honey', 'sweet'] },
      { char: '☕', keywords: ['coffee', 'tea', 'hot', 'drink', 'cafe'] },
      { char: '🍵', keywords: ['tea', 'green', 'drink'] },
      { char: '🧃', keywords: ['juice', 'box', 'drink'] },
      { char: '🥤', keywords: ['cup', 'straw', 'drink', 'soda'] },
      { char: '🧋', keywords: ['bubble', 'tea', 'boba'] },
      { char: '🍷', keywords: ['wine', 'glass', 'drink'] },
      { char: '🍸', keywords: ['cocktail', 'martini', 'drink'] },
      { char: '🍹', keywords: ['tropical', 'drink', 'cocktail'] },
      { char: '🍺', keywords: ['beer', 'mug', 'drink'] },
      { char: '🍻', keywords: ['cheers', 'beer', 'drink', 'toast'] },
      { char: '🥂', keywords: ['champagne', 'cheers', 'toast'] },
      { char: '🥛', keywords: ['milk', 'glass', 'drink'] },
    ],
  },
  {
    id: 'travel',
    label: 'Travel',
    emojis: [
      { char: '🚗', keywords: ['car', 'drive', 'vehicle'] },
      { char: '🚕', keywords: ['taxi', 'cab'] },
      { char: '🚌', keywords: ['bus'] },
      { char: '🚎', keywords: ['trolley', 'bus'] },
      { char: '🏎️', keywords: ['race', 'car', 'racing'] },
      { char: '🚓', keywords: ['police', 'car'] },
      { char: '🚑', keywords: ['ambulance'] },
      { char: '🚒', keywords: ['fire', 'truck'] },
      { char: '🛻', keywords: ['pickup', 'truck'] },
      { char: '🚚', keywords: ['truck', 'delivery'] },
      { char: '🏍️', keywords: ['motorcycle', 'bike'] },
      { char: '🛵', keywords: ['scooter', 'moped'] },
      { char: '🚲', keywords: ['bicycle', 'bike', 'cycle'] },
      { char: '🚂', keywords: ['train', 'locomotive'] },
      { char: '🚄', keywords: ['bullet', 'train', 'fast'] },
      { char: '🚇', keywords: ['metro', 'subway'] },
      { char: '✈️', keywords: ['airplane', 'plane', 'flight', 'travel'] },
      { char: '🛫', keywords: ['departure', 'airplane', 'takeoff'] },
      { char: '🛬', keywords: ['arrival', 'airplane', 'landing'] },
      { char: '🚁', keywords: ['helicopter'] },
      { char: '🚀', keywords: ['rocket', 'space', 'launch'] },
      { char: '🛸', keywords: ['ufo', 'alien', 'flying', 'saucer'] },
      { char: '⛵', keywords: ['sailboat', 'boat'] },
      { char: '🚢', keywords: ['ship', 'boat'] },
      { char: '🧳', keywords: ['luggage', 'suitcase', 'travel'] },
      { char: '🏠', keywords: ['house', 'home'] },
      { char: '🏡', keywords: ['house', 'garden', 'home'] },
      { char: '🏢', keywords: ['office', 'building', 'work'] },
      { char: '🏨', keywords: ['hotel', 'travel'] },
      { char: '🏪', keywords: ['convenience', 'store', 'shop'] },
      { char: '🏫', keywords: ['school', 'education'] },
      { char: '🏥', keywords: ['hospital', 'medical'] },
      { char: '🏦', keywords: ['bank', 'money'] },
      { char: '🏰', keywords: ['castle', 'european'] },
      { char: '🗼', keywords: ['tokyo', 'tower'] },
      { char: '🗽', keywords: ['statue', 'liberty', 'new york'] },
      { char: '⛪', keywords: ['church', 'religion'] },
      { char: '🕌', keywords: ['mosque', 'religion'] },
      { char: '⛩️', keywords: ['shrine', 'japanese'] },
      { char: '⛺', keywords: ['tent', 'camping'] },
      { char: '🌃', keywords: ['night', 'city', 'stars'] },
      { char: '🏙️', keywords: ['cityscape', 'skyline'] },
      { char: '🌄', keywords: ['sunrise', 'mountains'] },
      { char: '🌅', keywords: ['sunrise', 'morning'] },
      { char: '🌆', keywords: ['cityscape', 'dusk', 'sunset'] },
      { char: '🌇', keywords: ['sunset', 'city'] },
      { char: '🌉', keywords: ['bridge', 'night'] },
      { char: '🎡', keywords: ['ferris', 'wheel'] },
      { char: '🎢', keywords: ['roller', 'coaster'] },
      { char: '🗺️', keywords: ['map', 'world', 'travel'] },
      { char: '🧭', keywords: ['compass', 'navigation'] },
      { char: '🏔️', keywords: ['mountain', 'snow'] },
      { char: '🌋', keywords: ['volcano'] },
      { char: '🏕️', keywords: ['camping'] },
      { char: '🏖️', keywords: ['beach', 'umbrella', 'vacation'] },
      { char: '🏝️', keywords: ['island', 'desert', 'tropical'] },
      { char: '⏰', keywords: ['alarm', 'clock', 'time', 'wake'] },
      { char: '⌚', keywords: ['watch', 'time'] },
    ],
  },
  {
    id: 'activities',
    label: 'Activities',
    emojis: [
      { char: '⚽', keywords: ['soccer', 'football', 'ball', 'sport'] },
      { char: '🏀', keywords: ['basketball', 'ball', 'sport'] },
      { char: '🏈', keywords: ['football', 'american', 'sport'] },
      { char: '⚾', keywords: ['baseball', 'ball', 'sport'] },
      { char: '🥎', keywords: ['softball', 'sport'] },
      { char: '🎾', keywords: ['tennis', 'ball', 'sport'] },
      { char: '🏐', keywords: ['volleyball', 'sport'] },
      { char: '🏉', keywords: ['rugby', 'sport'] },
      { char: '🥏', keywords: ['frisbee', 'disc'] },
      { char: '🎱', keywords: ['pool', 'billiards', '8ball'] },
      { char: '🪀', keywords: ['yo-yo', 'toy'] },
      { char: '🏓', keywords: ['ping', 'pong', 'table', 'tennis'] },
      { char: '🏸', keywords: ['badminton', 'sport'] },
      { char: '🏒', keywords: ['hockey', 'ice', 'sport'] },
      { char: '🏑', keywords: ['field', 'hockey'] },
      { char: '🥍', keywords: ['lacrosse', 'sport'] },
      { char: '🏏', keywords: ['cricket', 'sport'] },
      { char: '🪃', keywords: ['boomerang'] },
      { char: '🥅', keywords: ['goal', 'net'] },
      { char: '⛳', keywords: ['golf', 'flag', 'hole'] },
      { char: '🪁', keywords: ['kite', 'fly'] },
      { char: '🏹', keywords: ['bow', 'arrow', 'archery'] },
      { char: '🎣', keywords: ['fishing', 'pole'] },
      { char: '🤿', keywords: ['diving', 'mask', 'snorkel'] },
      { char: '🥊', keywords: ['boxing', 'glove', 'fight'] },
      { char: '🥋', keywords: ['martial', 'arts', 'karate'] },
      { char: '🎽', keywords: ['running', 'shirt', 'sport'] },
      { char: '🛹', keywords: ['skateboard'] },
      { char: '🛼', keywords: ['roller', 'skate'] },
      { char: '🛷', keywords: ['sled', 'sleigh', 'winter'] },
      { char: '⛸️', keywords: ['ice', 'skate', 'winter'] },
      { char: '🥌', keywords: ['curling', 'stone'] },
      { char: '🎿', keywords: ['ski', 'winter', 'sport'] },
      { char: '⛷️', keywords: ['skier', 'ski', 'winter'] },
      { char: '🏂', keywords: ['snowboard', 'winter'] },
      { char: '🪂', keywords: ['parachute', 'skydive'] },
      { char: '🏋️', keywords: ['weight', 'lift', 'gym', 'fitness'] },
      { char: '🤼', keywords: ['wrestle', 'sport'] },
      { char: '🤸', keywords: ['cartwheel', 'gymnastics'] },
      { char: '⛹️', keywords: ['basketball', 'player'] },
      { char: '🤺', keywords: ['fencing', 'sword'] },
      { char: '🤾', keywords: ['handball'] },
      { char: '🏌️', keywords: ['golf', 'player'] },
      { char: '🏇', keywords: ['horse', 'racing'] },
      { char: '🧘', keywords: ['yoga', 'meditate', 'zen'] },
      { char: '🏄', keywords: ['surf', 'surfing', 'beach'] },
      { char: '🏊', keywords: ['swim', 'swimming'] },
      { char: '🤽', keywords: ['water', 'polo'] },
      { char: '🚣', keywords: ['row', 'boat'] },
      { char: '🧗', keywords: ['climb', 'climbing'] },
      { char: '🚵', keywords: ['mountain', 'bike'] },
      { char: '🚴', keywords: ['bike', 'cycling'] },
      { char: '🏆', keywords: ['trophy', 'win', 'champion', 'award'] },
      { char: '🥇', keywords: ['gold', 'medal', 'first', 'win'] },
      { char: '🥈', keywords: ['silver', 'medal', 'second'] },
      { char: '🥉', keywords: ['bronze', 'medal', 'third'] },
      { char: '🏅', keywords: ['medal', 'sport'] },
      { char: '🎖️', keywords: ['military', 'medal'] },
      { char: '🏵️', keywords: ['rosette', 'award'] },
      { char: '🎗️', keywords: ['reminder', 'ribbon'] },
      { char: '🎫', keywords: ['ticket', 'event'] },
      { char: '🎟️', keywords: ['admission', 'ticket'] },
      { char: '🎪', keywords: ['circus', 'tent'] },
      { char: '🤹', keywords: ['juggle', 'circus'] },
      { char: '🎭', keywords: ['theater', 'drama', 'masks', 'performing'] },
      { char: '🩰', keywords: ['ballet', 'dance'] },
      { char: '🎨', keywords: ['art', 'paint', 'palette', 'creative'] },
      { char: '🎬', keywords: ['movie', 'clapper', 'film', 'cinema'] },
      { char: '🎤', keywords: ['microphone', 'sing', 'karaoke', 'music'] },
      { char: '🎧', keywords: ['headphones', 'music', 'listen'] },
      { char: '🎼', keywords: ['music', 'score', 'notes'] },
      { char: '🎹', keywords: ['piano', 'keyboard', 'music'] },
      { char: '🥁', keywords: ['drum', 'music'] },
      { char: '🪘', keywords: ['long', 'drum'] },
      { char: '🎷', keywords: ['saxophone', 'music', 'jazz'] },
      { char: '🎺', keywords: ['trumpet', 'music'] },
      { char: '🪗', keywords: ['accordion', 'music'] },
      { char: '🎸', keywords: ['guitar', 'music', 'rock'] },
      { char: '🪕', keywords: ['banjo', 'music'] },
      { char: '🎻', keywords: ['violin', 'music', 'classical'] },
      { char: '🎲', keywords: ['dice', 'game', 'random'] },
      { char: '♟️', keywords: ['chess', 'pawn', 'game'] },
      { char: '🎯', keywords: ['target', 'dart', 'bullseye', 'goal'] },
      { char: '🎳', keywords: ['bowling', 'game'] },
      { char: '🎮', keywords: ['game', 'controller', 'video', 'gaming'] },
      { char: '🕹️', keywords: ['joystick', 'game', 'arcade'] },
      { char: '🎰', keywords: ['slot', 'machine', 'casino', 'gamble'] },
      { char: '🧩', keywords: ['puzzle', 'piece', 'game'] },
      { char: '🎈', keywords: ['balloon', 'party', 'celebrate'] },
      { char: '🎉', keywords: ['party', 'popper', 'celebrate', 'tada'] },
      { char: '🎊', keywords: ['confetti', 'ball', 'celebrate'] },
      { char: '🎁', keywords: ['gift', 'present', 'birthday', 'wrap'] },
      { char: '🎀', keywords: ['ribbon', 'bow', 'gift'] },
      { char: '🎃', keywords: ['pumpkin', 'halloween', 'jack'] },
      { char: '🎄', keywords: ['christmas', 'tree', 'holiday'] },
      { char: '🎆', keywords: ['fireworks', 'celebrate', 'new year'] },
      { char: '🎇', keywords: ['sparkler', 'fireworks'] },
      { char: '🧨', keywords: ['firecracker', 'explosive'] },
      { char: '✨', keywords: ['sparkles', 'shine', 'magic'] },
      { char: '🎋', keywords: ['tanabata', 'tree', 'wish'] },
      { char: '🎍', keywords: ['pine', 'decoration'] },
      { char: '🎎', keywords: ['dolls', 'japanese'] },
      { char: '🎏', keywords: ['carp', 'streamer'] },
      { char: '🎐', keywords: ['wind', 'chime'] },
      { char: '🎑', keywords: ['moon', 'viewing'] },
      { char: '🧧', keywords: ['red', 'envelope', 'lucky', 'money'] },
      { char: '🎀', keywords: ['ribbon'] },
      { char: '🎗️', keywords: ['ribbon', 'reminder'] },
      { char: '🎟️', keywords: ['ticket'] },
      { char: '🎫', keywords: ['ticket'] },
      { char: '🎖️', keywords: ['medal'] },
      { char: '🏆', keywords: ['trophy'] },
      { char: '🏅', keywords: ['medal'] },
      { char: '🥇', keywords: ['gold'] },
      { char: '🥈', keywords: ['silver'] },
      { char: '🥉', keywords: ['bronze'] },
    ],
  },
  {
    id: 'objects',
    label: 'Objects',
    emojis: [
      { char: '💡', keywords: ['light', 'bulb', 'idea', 'bright'] },
      { char: '🔦', keywords: ['flashlight', 'torch'] },
      { char: '🕯️', keywords: ['candle', 'light'] },
      { char: '🪔', keywords: ['diya', 'lamp'] },
      { char: '🧯', keywords: ['fire', 'extinguisher'] },
      { char: '🛢️', keywords: ['oil', 'drum'] },
      { char: '💸', keywords: ['money', 'wings', 'fly', 'spend'] },
      { char: '💵', keywords: ['dollar', 'money', 'cash'] },
      { char: '💴', keywords: ['yen', 'money'] },
      { char: '💶', keywords: ['euro', 'money'] },
      { char: '💷', keywords: ['pound', 'money'] },
      { char: '🪙', keywords: ['coin', 'money'] },
      { char: '💰', keywords: ['money', 'bag', 'rich'] },
      { char: '💳', keywords: ['credit', 'card', 'payment'] },
      { char: '💎', keywords: ['gem', 'diamond', 'jewel', 'precious'] },
      { char: '⚖️', keywords: ['balance', 'scale', 'justice'] },
      { char: '🪜', keywords: ['ladder'] },
      { char: '🧰', keywords: ['toolbox', 'tools'] },
      { char: '🪛', keywords: ['screwdriver', 'tool'] },
      { char: '🔧', keywords: ['wrench', 'tool', 'fix'] },
      { char: '🔨', keywords: ['hammer', 'tool', 'build'] },
      { char: '⚒️', keywords: ['hammer', 'pick', 'tool'] },
      { char: '🛠️', keywords: ['tools', 'hammer', 'wrench'] },
      { char: '⛏️', keywords: ['pick', 'mining'] },
      { char: '🪚', keywords: ['saw', 'tool'] },
      { char: '🔩', keywords: ['nut', 'bolt'] },
      { char: '⚙️', keywords: ['gear', 'settings', 'cog'] },
      { char: '🪤', keywords: ['mouse', 'trap'] },
      { char: '🧱', keywords: ['brick'] },
      { char: '⛓️', keywords: ['chains', 'link'] },
      { char: '🧲', keywords: ['magnet', 'attract'] },
      { char: '🔫', keywords: ['gun', 'water', 'pistol'] },
      { char: '💣', keywords: ['bomb', 'explosive'] },
      { char: '🧨', keywords: ['firecracker'] },
      { char: '🪓', keywords: ['axe', 'tool'] },
      { char: '🔪', keywords: ['knife', 'kitchen', 'cut'] },
      { char: '🗡️', keywords: ['dagger', 'sword'] },
      { char: '⚔️', keywords: ['crossed', 'swords', 'fight'] },
      { char: '🛡️', keywords: ['shield', 'protect'] },
      { char: '🚬', keywords: ['cigarette', 'smoke'] },
      { char: '⚰️', keywords: ['coffin', 'death'] },
      { char: '🪦', keywords: ['headstone', 'grave'] },
      { char: '⚱️', keywords: ['urn', 'funeral'] },
      { char: '🏺', keywords: ['amphora', 'vase'] },
      { char: '🔮', keywords: ['crystal', 'ball', 'fortune', 'magic'] },
      { char: '📿', keywords: ['prayer', 'beads'] },
      { char: '🧿', keywords: ['nazar', 'evil', 'eye', 'amulet'] },
      { char: '💈', keywords: ['barber', 'pole'] },
      { char: '⚗️', keywords: ['alembic', 'chemistry'] },
      { char: '🔭', keywords: ['telescope', 'space', 'stars'] },
      { char: '🔬', keywords: ['microscope', 'science'] },
      { char: '🕳️', keywords: ['hole'] },
      { char: '🩹', keywords: ['bandage', 'adhesive', 'hurt'] },
      { char: '🩺', keywords: ['stethoscope', 'doctor', 'medical'] },
      { char: '💊', keywords: ['pill', 'medicine', 'drug'] },
      { char: '💉', keywords: ['syringe', 'vaccine', 'shot'] },
      { char: '🩸', keywords: ['blood', 'drop', 'medical'] },
      { char: '🧬', keywords: ['dna', 'science', 'genetics'] },
      { char: '🦠', keywords: ['microbe', 'virus', 'germ'] },
      { char: '🧫', keywords: ['petri', 'dish', 'science'] },
      { char: '🧪', keywords: ['test', 'tube', 'science', 'lab'] },
      { char: '🌡️', keywords: ['thermometer', 'temperature'] },
      { char: '🧹', keywords: ['broom', 'clean'] },
      { char: '🪠', keywords: ['plunger'] },
      { char: '🧺', keywords: ['basket', 'laundry'] },
      { char: '🧻', keywords: ['toilet', 'paper'] },
      { char: '🪣', keywords: ['bucket'] },
      { char: '🧼', keywords: ['soap', 'clean', 'wash'] },
      { char: '🪥', keywords: ['toothbrush', 'dental'] },
      { char: '🧽', keywords: ['sponge', 'clean'] },
      { char: '🧴', keywords: ['lotion', 'bottle'] },
      { char: '🛁', keywords: ['bathtub', 'bath'] },
      { char: '🚿', keywords: ['shower'] },
      { char: '🛎️', keywords: ['bellhop', 'bell', 'hotel'] },
      { char: '🔑', keywords: ['key', 'lock', 'unlock'] },
      { char: '🗝️', keywords: ['old', 'key'] },
      { char: '🚪', keywords: ['door'] },
      { char: '🪑', keywords: ['chair', 'seat'] },
      { char: '🛋️', keywords: ['couch', 'sofa'] },
      { char: '🛏️', keywords: ['bed', 'sleep'] },
      { char: '🧸', keywords: ['teddy', 'bear', 'toy'] },
      { char: '🖼️', keywords: ['frame', 'picture', 'art'] },
      { char: '🪞', keywords: ['mirror'] },
      { char: '🪟', keywords: ['window'] },
      { char: '🛍️', keywords: ['shopping', 'bags'] },
      { char: '🛒', keywords: ['cart', 'shopping'] },
      { char: '🎁', keywords: ['gift', 'present'] },
      { char: '🎈', keywords: ['balloon'] },
      { char: '🎏', keywords: ['carp', 'streamer'] },
      { char: '🎀', keywords: ['ribbon'] },
      { char: '🪄', keywords: ['magic', 'wand'] },
      { char: '🪅', keywords: ['pinata', 'party'] },
      { char: '🪆', keywords: ['nesting', 'dolls'] },
      { char: '🧿', keywords: ['nazar'] },
      { char: '📱', keywords: ['phone', 'mobile', 'cell', 'iphone'] },
      { char: '📲', keywords: ['phone', 'arrow', 'call'] },
      { char: '☎️', keywords: ['telephone', 'phone'] },
      { char: '📞', keywords: ['phone', 'receiver'] },
      { char: '📟', keywords: ['pager'] },
      { char: '📠', keywords: ['fax', 'machine'] },
      { char: '🔋', keywords: ['battery', 'power', 'charge'] },
      { char: '🔌', keywords: ['plug', 'electric', 'power'] },
      { char: '💻', keywords: ['laptop', 'computer', 'work'] },
      { char: '🖥️', keywords: ['desktop', 'computer', 'monitor'] },
      { char: '🖨️', keywords: ['printer'] },
      { char: '⌨️', keywords: ['keyboard', 'type'] },
      { char: '🖱️', keywords: ['mouse', 'computer'] },
      { char: '🖲️', keywords: ['trackball'] },
      { char: '💽', keywords: ['minidisc'] },
      { char: '💾', keywords: ['floppy', 'disk', 'save'] },
      { char: '💿', keywords: ['cd', 'disc'] },
      { char: '📀', keywords: ['dvd', 'disc'] },
      { char: '🧮', keywords: ['abacus', 'calculate'] },
      { char: '🎥', keywords: ['movie', 'camera', 'film'] },
      { char: '🎞️', keywords: ['film', 'frames'] },
      { char: '📽️', keywords: ['projector', 'film'] },
      { char: '🎬', keywords: ['clapper', 'film'] },
      { char: '📺', keywords: ['tv', 'television'] },
      { char: '📷', keywords: ['camera', 'photo'] },
      { char: '📸', keywords: ['camera', 'flash', 'photo'] },
      { char: '📹', keywords: ['video', 'camera'] },
      { char: '📼', keywords: ['vhs', 'tape'] },
      { char: '🔍', keywords: ['magnifying', 'glass', 'search', 'zoom'] },
      { char: '🔎', keywords: ['magnifying', 'glass', 'search'] },
      { char: '🕯️', keywords: ['candle'] },
      { char: '💡', keywords: ['bulb', 'idea'] },
      { char: '🔦', keywords: ['flashlight'] },
      { char: '🏮', keywords: ['lantern', 'red'] },
      { char: '🪔', keywords: ['diya', 'lamp'] },
      { char: '📔', keywords: ['notebook', 'decorated'] },
      { char: '📕', keywords: ['book', 'closed', 'red'] },
      { char: '📖', keywords: ['book', 'open', 'read'] },
      { char: '📗', keywords: ['book', 'green'] },
      { char: '📘', keywords: ['book', 'blue'] },
      { char: '📙', keywords: ['book', 'orange'] },
      { char: '📚', keywords: ['books', 'library', 'read', 'study'] },
      { char: '📓', keywords: ['notebook'] },
      { char: '📒', keywords: ['ledger', 'notebook'] },
      { char: '📃', keywords: ['page', 'curl'] },
      { char: '📜', keywords: ['scroll', 'document'] },
      { char: '📄', keywords: ['page', 'document'] },
      { char: '📰', keywords: ['newspaper', 'news'] },
      { char: '🗞️', keywords: ['newspaper', 'rolled'] },
      { char: '📑', keywords: ['bookmark', 'tabs'] },
      { char: '🔖', keywords: ['bookmark', 'mark'] },
      { char: '🏷️', keywords: ['label', 'tag', 'price'] },
      { char: '💰', keywords: ['money', 'bag'] },
      { char: '🪙', keywords: ['coin'] },
      { char: '💴', keywords: ['yen'] },
      { char: '💵', keywords: ['dollar'] },
      { char: '💶', keywords: ['euro'] },
      { char: '💷', keywords: ['pound'] },
      { char: '💸', keywords: ['money', 'wings'] },
      { char: '💳', keywords: ['credit', 'card'] },
      { char: '🧾', keywords: ['receipt'] },
      { char: '💹', keywords: ['chart', 'yen', 'increase'] },
      { char: '✉️', keywords: ['envelope', 'email', 'mail'] },
      { char: '📧', keywords: ['email', 'e-mail'] },
      { char: '📨', keywords: ['envelope', 'incoming'] },
      { char: '📩', keywords: ['envelope', 'arrow'] },
      { char: '📤', keywords: ['outbox', 'tray', 'send'] },
      { char: '📥', keywords: ['inbox', 'tray', 'receive'] },
      { char: '📦', keywords: ['package', 'box', 'delivery'] },
      { char: '📫', keywords: ['mailbox', 'closed'] },
      { char: '📪', keywords: ['mailbox', 'closed', 'flag'] },
      { char: '📬', keywords: ['mailbox', 'open'] },
      { char: '📭', keywords: ['mailbox', 'open', 'flag'] },
      { char: '📮', keywords: ['postbox', 'mail'] },
      { char: '🗳️', keywords: ['ballot', 'box', 'vote'] },
      { char: '✏️', keywords: ['pencil', 'write', 'edit'] },
      { char: '✒️', keywords: ['pen', 'nib', 'write'] },
      { char: '🖋️', keywords: ['fountain', 'pen'] },
      { char: '🖊️', keywords: ['pen', 'write'] },
      { char: '🖌️', keywords: ['paintbrush', 'art'] },
      { char: '🖍️', keywords: ['crayon', 'draw'] },
      { char: '📝', keywords: ['memo', 'note', 'write', 'pencil'] },
      { char: '💼', keywords: ['briefcase', 'work', 'business'] },
      { char: '📁', keywords: ['folder', 'file'] },
      { char: '📂', keywords: ['folder', 'open'] },
      { char: '🗂️', keywords: ['card', 'index', 'dividers'] },
      { char: '📅', keywords: ['calendar', 'date'] },
      { char: '📆', keywords: ['calendar', 'tear', 'off'] },
      { char: '🗒️', keywords: ['spiral', 'notepad'] },
      { char: '🗓️', keywords: ['spiral', 'calendar'] },
      { char: '📇', keywords: ['card', 'index'] },
      { char: '📈', keywords: ['chart', 'increasing', 'growth', 'up'] },
      { char: '📉', keywords: ['chart', 'decreasing', 'down'] },
      { char: '📊', keywords: ['bar', 'chart', 'stats'] },
      { char: '📋', keywords: ['clipboard', 'list'] },
      { char: '📌', keywords: ['pushpin', 'pin'] },
      { char: '📍', keywords: ['pin', 'location', 'map'] },
      { char: '📎', keywords: ['paperclip', 'attach'] },
      { char: '🖇️', keywords: ['paperclips', 'linked'] },
      { char: '📏', keywords: ['ruler', 'straight'] },
      { char: '📐', keywords: ['ruler', 'triangular'] },
      { char: '✂️', keywords: ['scissors', 'cut'] },
      { char: '🗃️', keywords: ['card', 'file', 'box'] },
      { char: '🗄️', keywords: ['file', 'cabinet'] },
      { char: '🗑️', keywords: ['wastebasket', 'trash', 'delete'] },
      { char: '🔒', keywords: ['lock', 'locked', 'secure'] },
      { char: '🔓', keywords: ['unlock', 'open'] },
      { char: '🔏', keywords: ['lock', 'pen'] },
      { char: '🔐', keywords: ['lock', 'key', 'closed'] },
      { char: '🔑', keywords: ['key'] },
      { char: '🗝️', keywords: ['old', 'key'] },
      { char: '🔨', keywords: ['hammer'] },
      { char: '🪓', keywords: ['axe'] },
      { char: '⛏️', keywords: ['pick'] },
      { char: '⚒️', keywords: ['hammer', 'pick'] },
      { char: '🛠️', keywords: ['hammer', 'wrench'] },
      { char: '🗡️', keywords: ['dagger'] },
      { char: '⚔️', keywords: ['swords'] },
      { char: '🔫', keywords: ['pistol'] },
      { char: '🪃', keywords: ['boomerang'] },
      { char: '🏹', keywords: ['bow', 'arrow'] },
      { char: '🛡️', keywords: ['shield'] },
      { char: '🔧', keywords: ['wrench'] },
      { char: '🔩', keywords: ['nut', 'bolt'] },
      { char: '⚙️', keywords: ['gear'] },
      { char: '🗜️', keywords: ['clamp'] },
      { char: '⚖️', keywords: ['scale'] },
      { char: '🦯', keywords: ['probing', 'cane'] },
      { char: '🔗', keywords: ['link', 'chain', 'url'] },
      { char: '⛓️', keywords: ['chains'] },
      { char: '🪝', keywords: ['hook'] },
      { char: '🧰', keywords: ['toolbox'] },
      { char: '🧲', keywords: ['magnet'] },
      { char: '🪜', keywords: ['ladder'] },
    ],
  },

  {
    id: 'symbols',
    label: 'Symbols',
    emojis: [
      { char: '❤️', keywords: ['heart', 'red', 'love'] },
      { char: '🧡', keywords: ['heart', 'orange', 'love'] },
      { char: '💛', keywords: ['heart', 'yellow', 'love'] },
      { char: '💚', keywords: ['heart', 'green', 'love'] },
      { char: '💙', keywords: ['heart', 'blue', 'love'] },
      { char: '💜', keywords: ['heart', 'purple', 'love'] },
      { char: '🖤', keywords: ['heart', 'black', 'love'] },
      { char: '🤍', keywords: ['heart', 'white', 'love'] },
      { char: '🤎', keywords: ['heart', 'brown', 'love'] },
      { char: '💔', keywords: ['broken', 'heart', 'sad', 'breakup'] },
      { char: '❣️', keywords: ['heart', 'exclamation'] },
      { char: '💕', keywords: ['two', 'hearts', 'love'] },
      { char: '💞', keywords: ['revolving', 'hearts', 'love'] },
      { char: '💓', keywords: ['beating', 'heart', 'love'] },
      { char: '💗', keywords: ['growing', 'heart', 'love'] },
      { char: '💖', keywords: ['sparkling', 'heart', 'love'] },
      { char: '💘', keywords: ['cupid', 'heart', 'arrow', 'love'] },
      { char: '💝', keywords: ['heart', 'ribbon', 'gift', 'love'] },
      { char: '💟', keywords: ['heart', 'decoration'] },
      { char: '☮️', keywords: ['peace', 'symbol'] },
      { char: '✝️', keywords: ['cross', 'christian'] },
      { char: '☪️', keywords: ['star', 'crescent', 'islam'] },
      { char: '🕉️', keywords: ['om', 'hindu'] },
      { char: '☸️', keywords: ['wheel', 'dharma', 'buddhist'] },
      { char: '✡️', keywords: ['star', 'david', 'jewish'] },
      { char: '🔯', keywords: ['dotted', 'six', 'pointed', 'star'] },
      { char: '🕎', keywords: ['menorah', 'hanukkah'] },
      { char: '☯️', keywords: ['yin', 'yang', 'balance'] },
      { char: '☦️', keywords: ['orthodox', 'cross'] },
      { char: '🛐', keywords: ['place', 'worship', 'religion'] },
      { char: '⛎', keywords: ['ophiuchus', 'zodiac'] },
      { char: '♈', keywords: ['aries', 'zodiac'] },
      { char: '♉', keywords: ['taurus', 'zodiac'] },
      { char: '♊', keywords: ['gemini', 'zodiac'] },
      { char: '♋', keywords: ['cancer', 'zodiac'] },
      { char: '♌', keywords: ['leo', 'zodiac'] },
      { char: '♍', keywords: ['virgo', 'zodiac'] },
      { char: '♎', keywords: ['libra', 'zodiac'] },
      { char: '♏', keywords: ['scorpio', 'zodiac'] },
      { char: '♐', keywords: ['sagittarius', 'zodiac'] },
      { char: '♑', keywords: ['capricorn', 'zodiac'] },
      { char: '♒', keywords: ['aquarius', 'zodiac'] },
      { char: '♓', keywords: ['pisces', 'zodiac'] },
      { char: '🔀', keywords: ['shuffle', 'tracks'] },
      { char: '🔁', keywords: ['repeat', 'loop'] },
      { char: '🔂', keywords: ['repeat', 'one'] },
      { char: '▶️', keywords: ['play', 'button', 'start'] },
      { char: '⏩', keywords: ['fast', 'forward'] },
      { char: '⏭️', keywords: ['next', 'track'] },
      { char: '⏯️', keywords: ['play', 'pause'] },
      { char: '◀️', keywords: ['reverse', 'back'] },
      { char: '⏪', keywords: ['rewind', 'fast'] },
      { char: '⏮️', keywords: ['previous', 'track'] },
      { char: '🔼', keywords: ['up', 'button'] },
      { char: '⏫', keywords: ['fast', 'up'] },
      { char: '🔽', keywords: ['down', 'button'] },
      { char: '⏬', keywords: ['fast', 'down'] },
      { char: '⏸️', keywords: ['pause', 'button'] },
      { char: '⏹️', keywords: ['stop', 'button'] },
      { char: '⏺️', keywords: ['record', 'button'] },
      { char: '⏏️', keywords: ['eject', 'button'] },
      { char: '🎦', keywords: ['cinema', 'film'] },
      { char: '🔅', keywords: ['dim', 'button', 'brightness'] },
      { char: '🔆', keywords: ['bright', 'button', 'brightness'] },
      { char: '📶', keywords: ['signal', 'bars', 'wifi'] },
      { char: '📳', keywords: ['vibration', 'mode'] },
      { char: '📴', keywords: ['mobile', 'phone', 'off'] },
      { char: '♀️', keywords: ['female', 'sign', 'woman'] },
      { char: '♂️', keywords: ['male', 'sign', 'man'] },
      { char: '⚧️', keywords: ['transgender', 'symbol'] },
      { char: '✖️', keywords: ['multiply', 'x', 'cross', 'cancel'] },
      { char: '➕', keywords: ['plus', 'add'] },
      { char: '➖', keywords: ['minus', 'subtract'] },
      { char: '➗', keywords: ['divide'] },
      { char: '♾️', keywords: ['infinity', 'forever'] },
      { char: '‼️', keywords: ['double', 'exclamation'] },
      { char: '⁉️', keywords: ['exclamation', 'question'] },
      { char: '❓', keywords: ['question', 'mark'] },
      { char: '❔', keywords: ['white', 'question'] },
      { char: '❕', keywords: ['white', 'exclamation'] },
      { char: '❗', keywords: ['exclamation', 'mark', 'important'] },
      { char: '〰️', keywords: ['wavy', 'dash'] },
      { char: '💱', keywords: ['currency', 'exchange'] },
      { char: '💲', keywords: ['heavy', 'dollar', 'sign', 'money'] },
      { char: '⚕️', keywords: ['medical', 'symbol'] },
      { char: '♻️', keywords: ['recycle', 'green'] },
      { char: '⚜️', keywords: ['fleur', 'de', 'lis'] },
      { char: '🔱', keywords: ['trident', 'emblem'] },
      { char: '📛', keywords: ['name', 'badge'] },
      { char: '🔰', keywords: ['japanese', 'beginner'] },
      { char: '⭕', keywords: ['hollow', 'red', 'circle', 'o'] },
      { char: '✅', keywords: ['check', 'mark', 'button', 'done', 'yes'] },
      { char: '☑️', keywords: ['check', 'box', 'done'] },
      { char: '✔️', keywords: ['check', 'mark', 'done', 'yes'] },
      { char: '❌', keywords: ['cross', 'mark', 'x', 'no', 'wrong'] },
      { char: '❎', keywords: ['cross', 'mark', 'button', 'no'] },
      { char: '➰', keywords: ['curly', 'loop'] },
      { char: '➿', keywords: ['double', 'curly', 'loop'] },
      { char: '〽️', keywords: ['part', 'alternation'] },
      { char: '✳️', keywords: ['eight', 'spoked', 'asterisk'] },
      { char: '✴️', keywords: ['eight', 'pointed', 'star'] },
      { char: '❇️', keywords: ['sparkle'] },
      { char: '©️', keywords: ['copyright'] },
      { char: '®️', keywords: ['registered'] },
      { char: '™️', keywords: ['trademark'] },
      { char: '#️⃣', keywords: ['hash', 'number', 'sign', 'pound'] },
      { char: '*️⃣', keywords: ['asterisk', 'keycap'] },
      { char: '0️⃣', keywords: ['zero', 'keycap'] },
      { char: '1️⃣', keywords: ['one', 'keycap'] },
      { char: '2️⃣', keywords: ['two', 'keycap'] },
      { char: '3️⃣', keywords: ['three', 'keycap'] },
      { char: '4️⃣', keywords: ['four', 'keycap'] },
      { char: '5️⃣', keywords: ['five', 'keycap'] },
      { char: '6️⃣', keywords: ['six', 'keycap'] },
      { char: '7️⃣', keywords: ['seven', 'keycap'] },
      { char: '8️⃣', keywords: ['eight', 'keycap'] },
      { char: '9️⃣', keywords: ['nine', 'keycap'] },
      { char: '🔟', keywords: ['ten', 'keycap'] },
      { char: '🔠', keywords: ['input', 'latin', 'uppercase'] },
      { char: '🔡', keywords: ['input', 'latin', 'lowercase'] },
      { char: '🔢', keywords: ['input', 'numbers'] },
      { char: '🔣', keywords: ['input', 'symbols'] },
      { char: '🔤', keywords: ['input', 'latin', 'letters'] },
      { char: '🅰️', keywords: ['a', 'button', 'blood'] },
      { char: '🆎', keywords: ['ab', 'button', 'blood'] },
      { char: '🅱️', keywords: ['b', 'button', 'blood'] },
      { char: '🆑', keywords: ['cl', 'button', 'clear'] },
      { char: '🆒', keywords: ['cool', 'button'] },
      { char: '🆓', keywords: ['free', 'button'] },
      { char: 'ℹ️', keywords: ['information', 'info'] },
      { char: '🆔', keywords: ['id', 'button'] },
      { char: 'Ⓜ️', keywords: ['circled', 'm'] },
      { char: '🆕', keywords: ['new', 'button'] },
      { char: '🆖', keywords: ['ng', 'button'] },
      { char: '🅾️', keywords: ['o', 'button', 'blood'] },
      { char: '🆗', keywords: ['ok', 'button', 'yes'] },
      { char: '🅿️', keywords: ['p', 'button', 'parking'] },
      { char: '🆘', keywords: ['sos', 'help', 'emergency'] },
      { char: '🆙', keywords: ['up', 'button'] },
      { char: '🆚', keywords: ['vs', 'versus'] },
      { char: '🈁', keywords: ['japanese', 'here'] },
      { char: '🈂️', keywords: ['japanese', 'service'] },
      { char: '🈷️', keywords: ['japanese', 'monthly'] },
      { char: '🈶', keywords: ['japanese', 'not', 'free'] },
      { char: '🈯', keywords: ['japanese', 'reserved'] },
      { char: '🉐', keywords: ['japanese', 'bargain'] },
      { char: '🈹', keywords: ['japanese', 'discount'] },
      { char: '🈚', keywords: ['japanese', 'free'] },
      { char: '🈲', keywords: ['japanese', 'prohibited'] },
      { char: '🉑', keywords: ['japanese', 'acceptable'] },
      { char: '🈸', keywords: ['japanese', 'application'] },
      { char: '🈴', keywords: ['japanese', 'passing'] },
      { char: '🈳', keywords: ['japanese', 'vacancy'] },
      { char: '㊗️', keywords: ['japanese', 'congratulations'] },
      { char: '㊙️', keywords: ['japanese', 'secret'] },
      { char: '🈺', keywords: ['japanese', 'open'] },
      { char: '🈵', keywords: ['japanese', 'no', 'vacancy'] },
      { char: '🔴', keywords: ['red', 'circle'] },
      { char: '🟠', keywords: ['orange', 'circle'] },
      { char: '🟡', keywords: ['yellow', 'circle'] },
      { char: '🟢', keywords: ['green', 'circle'] },
      { char: '🔵', keywords: ['blue', 'circle'] },
      { char: '🟣', keywords: ['purple', 'circle'] },
      { char: '🟤', keywords: ['brown', 'circle'] },
      { char: '⚫', keywords: ['black', 'circle'] },
      { char: '⚪', keywords: ['white', 'circle'] },
      { char: '🟥', keywords: ['red', 'square'] },
      { char: '🟧', keywords: ['orange', 'square'] },
      { char: '🟨', keywords: ['yellow', 'square'] },
      { char: '🟩', keywords: ['green', 'square'] },
      { char: '🟦', keywords: ['blue', 'square'] },
      { char: '🟪', keywords: ['purple', 'square'] },
      { char: '🟫', keywords: ['brown', 'square'] },
      { char: '⬛', keywords: ['black', 'large', 'square'] },
      { char: '⬜', keywords: ['white', 'large', 'square'] },
      { char: '◼️', keywords: ['black', 'medium', 'square'] },
      { char: '◻️', keywords: ['white', 'medium', 'square'] },
      { char: '◾', keywords: ['black', 'medium', 'small', 'square'] },
      { char: '◽', keywords: ['white', 'medium', 'small', 'square'] },
      { char: '▪️', keywords: ['black', 'small', 'square'] },
      { char: '▫️', keywords: ['white', 'small', 'square'] },
      { char: '🔶', keywords: ['orange', 'diamond'] },
      { char: '🔷', keywords: ['blue', 'diamond'] },
      { char: '🔸', keywords: ['small', 'orange', 'diamond'] },
      { char: '🔹', keywords: ['small', 'blue', 'diamond'] },
      { char: '🔺', keywords: ['red', 'triangle', 'up'] },
      { char: '🔻', keywords: ['red', 'triangle', 'down'] },
      { char: '💠', keywords: ['diamond', 'dot'] },
      { char: '🔘', keywords: ['radio', 'button'] },
      { char: '🔳', keywords: ['white', 'square', 'button'] },
      { char: '🔲', keywords: ['black', 'square', 'button'] },
      { char: '🏁', keywords: ['checkered', 'flag', 'race', 'finish'] },
      { char: '🚩', keywords: ['triangular', 'flag', 'red'] },
      { char: '🎌', keywords: ['crossed', 'flags', 'japan'] },
      { char: '🏴', keywords: ['black', 'flag'] },
      { char: '🏳️', keywords: ['white', 'flag'] },
      { char: '🏳️‍🌈', keywords: ['rainbow', 'flag', 'pride'] },
      { char: '🏳️‍⚧️', keywords: ['transgender', 'flag'] },
      { char: '🏴‍☠️', keywords: ['pirate', 'flag'] },
      { char: '👍', keywords: ['thumbs', 'up'] },
      { char: '👎', keywords: ['thumbs', 'down'] },
      { char: '👏', keywords: ['clap'] },
      { char: '🙌', keywords: ['raise', 'hands'] },
      { char: '🤝', keywords: ['handshake'] },
      { char: '🙏', keywords: ['pray', 'thanks'] },
      { char: '💪', keywords: ['muscle', 'strong'] },
      { char: '🔥', keywords: ['fire', 'lit', 'hot'] },
      { char: '✨', keywords: ['sparkles'] },
      { char: '⭐', keywords: ['star'] },
      { char: '💯', keywords: ['hundred', 'points', 'perfect', 'score'] },
      { char: '✅', keywords: ['check'] },
      { char: '❌', keywords: ['cross'] },
      { char: '⚡', keywords: ['lightning'] },
      { char: '🎯', keywords: ['target'] },
      { char: '🚀', keywords: ['rocket'] },
      { char: '💡', keywords: ['idea'] },
      { char: '🎉', keywords: ['party'] },
      { char: '❤️', keywords: ['love'] },
      { char: '💔', keywords: ['heartbreak'] },
      { char: '🔔', keywords: ['bell', 'notification'] },
      { char: '🔕', keywords: ['bell', 'slash', 'mute'] },
      { char: '📣', keywords: ['megaphone', 'announce'] },
      { char: '📢', keywords: ['loudspeaker', 'announce'] },
      { char: '💬', keywords: ['speech', 'bubble', 'comment', 'chat'] },
      { char: '💭', keywords: ['thought', 'bubble', 'think'] },
      { char: '🗯️', keywords: ['anger', 'bubble', 'mad'] },
      { char: '♠️', keywords: ['spade', 'suit', 'cards'] },
      { char: '♣️', keywords: ['club', 'suit', 'cards'] },
      { char: '♥️', keywords: ['heart', 'suit', 'cards'] },
      { char: '♦️', keywords: ['diamond', 'suit', 'cards'] },
      { char: '🃏', keywords: ['joker', 'cards'] },
      { char: '🎴', keywords: ['flower', 'playing', 'cards'] },
      { char: '🀄', keywords: ['mahjong', 'red', 'dragon'] },
      { char: '🔇', keywords: ['muted', 'speaker'] },
      { char: '🔈', keywords: ['speaker', 'low'] },
      { char: '🔉', keywords: ['speaker', 'medium'] },
      { char: '🔊', keywords: ['speaker', 'high', 'loud'] },
      { char: '🎵', keywords: ['musical', 'note', 'music'] },
      { char: '🎶', keywords: ['musical', 'notes', 'music'] },
      { char: '💤', keywords: ['zzz', 'sleep', 'tired'] },
      { char: '💢', keywords: ['anger', 'symbol', 'mad'] },
      { char: '💨', keywords: ['dash', 'fast', 'wind'] },
      { char: '💫', keywords: ['dizzy', 'star'] },
      { char: '💦', keywords: ['sweat', 'droplets'] },
      { char: '💥', keywords: ['collision', 'boom'] },
      { char: '🕳️', keywords: ['hole'] },
      { char: '💣', keywords: ['bomb'] },
      { char: '💬', keywords: ['speech'] },
      { char: '👁️‍🗨️', keywords: ['eye', 'speech', 'bubble'] },
      { char: '🗨️', keywords: ['left', 'speech', 'bubble'] },
      { char: '🗯️', keywords: ['right', 'anger', 'bubble'] },
      { char: '💭', keywords: ['thought'] },
      { char: '💤', keywords: ['sleep'] },
    ],
  },
  {
    id: 'flags',
    label: 'Flags',
    emojis: [
      { char: '🏳️', keywords: ['white', 'flag'] },
      { char: '🏴', keywords: ['black', 'flag'] },
      { char: '🏁', keywords: ['checkered', 'flag'] },
      { char: '🚩', keywords: ['triangular', 'flag'] },
      { char: '🏳️‍🌈', keywords: ['rainbow', 'flag', 'pride', 'lgbt'] },
      { char: '🏳️‍⚧️', keywords: ['transgender', 'flag'] },
      { char: '🏴‍☠️', keywords: ['pirate', 'flag'] },
      { char: '🇺🇸', keywords: ['united', 'states', 'usa', 'america', 'flag'] },
      { char: '🇬🇧', keywords: ['united', 'kingdom', 'uk', 'britain', 'flag'] },
      { char: '🇨🇦', keywords: ['canada', 'flag'] },
      { char: '🇦🇺', keywords: ['australia', 'flag'] },
      { char: '🇩🇪', keywords: ['germany', 'flag'] },
      { char: '🇫🇷', keywords: ['france', 'flag'] },
      { char: '🇪🇸', keywords: ['spain', 'flag'] },
      { char: '🇮🇹', keywords: ['italy', 'flag'] },
      { char: '🇯🇵', keywords: ['japan', 'flag'] },
      { char: '🇰🇷', keywords: ['south', 'korea', 'flag'] },
      { char: '🇨🇳', keywords: ['china', 'flag'] },
      { char: '🇮🇳', keywords: ['india', 'flag'] },
      { char: '🇧🇷', keywords: ['brazil', 'flag'] },
      { char: '🇲🇽', keywords: ['mexico', 'flag'] },
      { char: '🇷🇺', keywords: ['russia', 'flag'] },
      { char: '🇺🇦', keywords: ['ukraine', 'flag'] },
      { char: '🇵🇱', keywords: ['poland', 'flag'] },
      { char: '🇳🇱', keywords: ['netherlands', 'flag'] },
      { char: '🇧🇪', keywords: ['belgium', 'flag'] },
      { char: '🇸🇪', keywords: ['sweden', 'flag'] },
      { char: '🇳🇴', keywords: ['norway', 'flag'] },
      { char: '🇩🇰', keywords: ['denmark', 'flag'] },
      { char: '🇫🇮', keywords: ['finland', 'flag'] },
      { char: '🇨🇭', keywords: ['switzerland', 'flag'] },
      { char: '🇦🇹', keywords: ['austria', 'flag'] },
      { char: '🇵🇹', keywords: ['portugal', 'flag'] },
      { char: '🇬🇷', keywords: ['greece', 'flag'] },
      { char: '🇹🇷', keywords: ['turkey', 'flag'] },
      { char: '🇮🇱', keywords: ['israel', 'flag'] },
      { char: '🇸🇦', keywords: ['saudi', 'arabia', 'flag'] },
      { char: '🇦🇪', keywords: ['uae', 'emirates', 'flag'] },
      { char: '🇪🇬', keywords: ['egypt', 'flag'] },
      { char: '🇿🇦', keywords: ['south', 'africa', 'flag'] },
      { char: '🇳🇬', keywords: ['nigeria', 'flag'] },
      { char: '🇰🇪', keywords: ['kenya', 'flag'] },
      { char: '🇦🇷', keywords: ['argentina', 'flag'] },
      { char: '🇨🇱', keywords: ['chile', 'flag'] },
      { char: '🇨🇴', keywords: ['colombia', 'flag'] },
      { char: '🇵🇪', keywords: ['peru', 'flag'] },
      { char: '🇻🇪', keywords: ['venezuela', 'flag'] },
      { char: '🇹🇭', keywords: ['thailand', 'flag'] },
      { char: '🇻🇳', keywords: ['vietnam', 'flag'] },
      { char: '🇵🇭', keywords: ['philippines', 'flag'] },
      { char: '🇮🇩', keywords: ['indonesia', 'flag'] },
      { char: '🇲🇾', keywords: ['malaysia', 'flag'] },
      { char: '🇸🇬', keywords: ['singapore', 'flag'] },
      { char: '🇳🇿', keywords: ['new', 'zealand', 'flag'] },
      { char: '🇮🇪', keywords: ['ireland', 'flag'] },
      { char: '🇨🇿', keywords: ['czech', 'flag'] },
      { char: '🇭🇺', keywords: ['hungary', 'flag'] },
      { char: '🇷🇴', keywords: ['romania', 'flag'] },
      { char: '🇧🇬', keywords: ['bulgaria', 'flag'] },
      { char: '🇭🇷', keywords: ['croatia', 'flag'] },
      { char: '🇷🇸', keywords: ['serbia', 'flag'] },
      { char: '🇸🇰', keywords: ['slovakia', 'flag'] },
      { char: '🇸🇮', keywords: ['slovenia', 'flag'] },
      { char: '🇱🇹', keywords: ['lithuania', 'flag'] },
      { char: '🇱🇻', keywords: ['latvia', 'flag'] },
      { char: '🇪🇪', keywords: ['estonia', 'flag'] },
      { char: '🇮🇸', keywords: ['iceland', 'flag'] },
      { char: '🇱🇺', keywords: ['luxembourg', 'flag'] },
      { char: '🇲🇹', keywords: ['malta', 'flag'] },
      { char: '🇨🇾', keywords: ['cyprus', 'flag'] },
      { char: '🇵🇰', keywords: ['pakistan', 'flag'] },
      { char: '🇧🇩', keywords: ['bangladesh', 'flag'] },
      { char: '🇱🇰', keywords: ['sri', 'lanka', 'flag'] },
      { char: '🇳🇵', keywords: ['nepal', 'flag'] },
      { char: '🇶🇦', keywords: ['qatar', 'flag'] },
      { char: '🇰🇼', keywords: ['kuwait', 'flag'] },
      { char: '🇴🇲', keywords: ['oman', 'flag'] },
      { char: '🇧🇭', keywords: ['bahrain', 'flag'] },
      { char: '🇯🇴', keywords: ['jordan', 'flag'] },
      { char: '🇱🇧', keywords: ['lebanon', 'flag'] },
      { char: '🇲🇦', keywords: ['morocco', 'flag'] },
      { char: '🇹🇳', keywords: ['tunisia', 'flag'] },
      { char: '🇩🇿', keywords: ['algeria', 'flag'] },
      { char: '🇪🇹', keywords: ['ethiopia', 'flag'] },
      { char: '🇬🇭', keywords: ['ghana', 'flag'] },
      { char: '🇨🇷', keywords: ['costa', 'rica', 'flag'] },
      { char: '🇵🇦', keywords: ['panama', 'flag'] },
      { char: '🇺🇾', keywords: ['uruguay', 'flag'] },
      { char: '🇵🇷', keywords: ['puerto', 'rico', 'flag'] },
      { char: '🇭🇰', keywords: ['hong', 'kong', 'flag'] },
      { char: '🇹🇼', keywords: ['taiwan', 'flag'] },
    ],
  },
]

export const EMOJI_CATEGORIES: EmojiCategory[] = EMOJI_CATEGORIES_SOURCE.map(category => ({
  ...category,
  emojis: dedupeEmojiItems(category.emojis),
}))

export const EMOJI_CATEGORY_ICONS: Record<Exclude<EmojiCategoryId, 'recent'>, string> = {
  smileys: '😀',
  people: '👋',
  animals: '🐶',
  food: '🍕',
  travel: '✈️',
  activities: '⚽',
  objects: '💡',
  symbols: '❤️',
  flags: '🏁',
}

export function loadRecentEmojis(): EmojiItem[] {
  if (typeof window === 'undefined') return []
  try {
    const raw = localStorage.getItem(EMOJI_RECENT_STORAGE_KEY)
    if (!raw) return []
    const parsed = JSON.parse(raw) as unknown
    if (!Array.isArray(parsed)) return []
    return dedupeEmojiItems(
      parsed
        .filter(
          (item): item is EmojiItem =>
            typeof item === 'object' &&
            item !== null &&
            typeof (item as EmojiItem).char === 'string' &&
            Array.isArray((item as EmojiItem).keywords),
        )
        .slice(0, EMOJI_RECENT_MAX),
    )
  } catch {
    return []
  }
}

export function saveRecentEmoji(emoji: EmojiItem): void {
  if (typeof window === 'undefined') return
  try {
    const current = loadRecentEmojis().filter(item => item.char !== emoji.char)
    const next = [emoji, ...current].slice(0, EMOJI_RECENT_MAX)
    localStorage.setItem(EMOJI_RECENT_STORAGE_KEY, JSON.stringify(next))
  } catch {
    // localStorage may be unavailable
  }
}

export function searchEmojis(query: string, recent: EmojiItem[]): EmojiItem[] {
  const normalized = query.trim().toLowerCase()
  if (!normalized) return []

  const seen = new Set<string>()
  const results: EmojiItem[] = []

  const add = (item: EmojiItem) => {
    if (seen.has(item.char)) return
    seen.add(item.char)
    results.push(item)
  }

  for (const item of recent) {
    if (item.keywords.some(keyword => keyword.includes(normalized))) {
      add(item)
    }
  }

  for (const category of EMOJI_CATEGORIES) {
    for (const item of category.emojis) {
      if (item.keywords.some(keyword => keyword.includes(normalized))) {
        add(item)
      }
    }
  }

  return results
}

export function getAllEmojis(): EmojiItem[] {
  const seen = new Set<string>()
  const all: EmojiItem[] = []

  for (const category of EMOJI_CATEGORIES) {
    for (const item of category.emojis) {
      if (seen.has(item.char)) continue
      seen.add(item.char)
      all.push(item)
    }
  }

  return all
}
